sudo: required

services:
  - docker

before_install:
  - docker build -t nunocf/learn-docker -f Dockerfile.dev .

script:
  - docker run nunocf/learn-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learn-docker"
  env: "LearnDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-852293823418"
  bucket_path: "learn-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"